### ISSUE TITLE
dear author, data preprocessing, thanks

### ISSUE THREAD

**Issue by emilyemliyM** [kamanphoebe/MotionDetection#2]
![image](https://user-images.githubusercontent.com/88700988/181411772-f94e9d10-0e71-4d47-9df5-ad2bb5fef143.png)

I wanna to know that the images are from  "Nuscenes" or "NuImage"

What's more, How to generate the labels? Could I get an script?

Thanks!

**Comment by kamanphoebe** [comment]
Hi!

Since this part of the guideline focus only on applying our model to your **own** images, you should first collect the images yourself. Your labels should contain the paths of your images and the coordinates of the objects as listed in `demo_label.csv`, while excluding the motion status. We obtained these information directly from the nuScenes dataset. Yet you have to generate the labels manually if you use your own data. In this case, some opensource object detection algorithms might be helpful to you.

Instead, if you are interested in constructing the dataset based on the nuScenes dataset, the "[Implement the complete pipeline](https://github.com/kamanphoebe/MotionDetection#implement-the-complete-pipeline)" part in the guideline would help you go through the whole process and all the codes necessary are provided in this repository.
