### ISSUE TITLE
question about choose the param like the "min_dist" or "max_dist". 

### ISSUE THREAD

**Issue by emilyemliyM** [kamanphoebe/MotionDetection#5]
Really thanks for the quick reply.

Dear author,
![image](https://user-images.githubusercontent.com/88700988/182397468-606f78ce-a04a-4b0a-9330-604550fc1d95.png)

I wanna know how to choose the param like the "min_dist" or "max_dist".  It is according to the category of "vehicle" ?

BTW, if I also want to use the category "pedestrain" , how to set the params above?

Really thanks.

**Comment by kamanphoebe** [comment]
The value of those six parameters in your screenshot can be chosen according to your need. Specifically, we chose the distance range to be [30, 70] since we are focusing on the remote objects. Besides, this range also includes most of our targets; we had studied the distance distribution of the targets before setting these parameters, yet I don't have the related script on hand. Consider writing one for "pedestrain" before using it and hopefully it will give you a sense of how to set up the value. Some of the code have to be modified if you want to apply different values for vehicle and pedestrain (this would be another story).

Just as a reminder, nuScenes has labeled the motion status for every vehicle and human. [Here](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_nuscenes.md#attributes) is the detailed introduction. We didn't make use of it (and instead setting a threshold velocity manually) just because we didn't notice it at that time. Therefore, if you are thinking about the suitable value of threshold velocity for pedestrian, I would strongly recommend rather using the information provided by nuScenes.
